import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Mono } from "next/font/google";

import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const notoSansMono = Noto_Sans_Mono({
  variable: "--font-noto-sans-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoSansMono.variable} ${notoSans.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
